### ISSUE TITLE
Bot becomes dormant after amount of time even though still online on Bluemix

### ISSUE THREAD

**Issue by Stuartkenworthy** [rampatra/jbot#43] opened 2017-05-10 09:51 UTC
Ive noticed that my bot keeps going offline on slack and so when a user tries to message it, it does not give any output back, when checking Bluemix, which is where I have deployed the bot, the app is still reported as online and there are no logs reporting any issues, the only way I have found to resolve this is to restart the bot on Bluemix, this then makes it active on Slack again and allows a user to message it, but then after a while the same thing will happen again.

**Comment by ramswaroop** [comment] 2017-05-10 14:40
HI @Stuartkenworthy, may I know which Bluemix plan are you currently using for the bot? Because I have faced the same issue on Heroku free version but not on the paid one. I think they halt it or something if it's idle. Am not completely sure if this is the cause but its what I deducted from my observation.

**Comment by Stuartkenworthy** [comment] 2017-05-10 15:04
It is the default plan I am using on the Stage1 version of Bluemix

**Comment by Stuartkenworthy** [comment] 2017-05-10 15:07
It is the default plan I am using on the Stage1 version of Bluemix

**Comment by ramswaroop** [comment] 2017-05-10 22:30
Is the default plan a free one or you pay some amount?

**Comment by Stuartkenworthy** [comment] 2017-05-11 07:53
It is the one that gives you a 30 day free trial, but as an IBM employee that free trial doesnt end

**Comment by ramswaroop** [comment] 2017-05-11 11:08
Hmm, that's the thing, I can't guarantee for a free plan as I have had the same issue with Heroku free plan as well but no problems with the paid one. I think the free plan halt the application if they find it idle for some time. Again, am not completely sure but this is what I observed.

**Comment by Stuartkenworthy** [comment] 2017-05-11 12:15
Thank you, I can raise a ticket against Bluemix and see if they can provide any more information

**Comment by tcarlson25** [comment] 2017-08-15 15:13
I would like to resolve this issue as well. Currently having trouble here. @Stuartkenworthy did you find a fix?

**Comment by ramswaroop** [comment] 2017-08-15 20:49
@tcarlson25 what server do you use to host your bot?

**Comment by tcarlson25** [comment] 2017-08-15 20:52
Liberty Server

**Comment by ramswaroop** [comment] 2017-08-15 20:53
Is it free or paid one?

**Comment by tcarlson25** [comment] 2017-08-15 20:54
Its the free plan, but as an employee it is an extended free plan

**Comment by ramswaroop** [comment] 2017-08-15 21:04
Hmm, I can't be 100% sure but most free plans cut the connection on idle.

**Comment by ejwood79** [comment] 2017-08-30 21:47
I'm encountering a similar issue, and we're hosting the bot on an EC2 instance that we pay for. I wouldn't expect it to get cut off.

I'm going to watch it a bit more closely though to see what the dormant period is.

**Comment by thiagobaluGit** [comment] 2017-09-11 11:49
Hi,
I am having the same issue too!
When I log the error it shows:

08-09-2017;04:15:04 [WebSocketClient-SecureIO-2] DEBUG me.ramswaroop.jbot.core.slack.Bot.afterConnectionClosed [139] - WebSocket closed: StandardWebSocketSession[id=0, uri=null], Close Status: CloseStatus[code=1006, reason=Unexpected end of stream]

After this, the bot won´t respond to any command.

Any solutions yet?

Thanks!

**Comment by ramswaroop** [comment] 2017-09-11 13:49
@thiagobaluGit did you see any other error before this? I think I have to debug this issue in depth as many are facing this issue.

**Comment by thiagobaluGit** [comment] 2017-09-11 13:59
Just this one below, @ramswaroop !

This error occurs before the WebSocket was closing (many times):
`Exception: 
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of me.ramswaroop.jbot.core.slack.models.Message: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"type":"message","message":{"type":"message","user":"U6PDZCV9T","text":"test","title_link":"test","text":"test","fallback":"test","thumb_url":"https:\/\/us.v-cdn.net\/6025736\/uploads\/SNG70YZ1UN0M.jpg","from_url":"test","thumb_width":1200,"thumb_height":630,"service_icon":"https:\/\/us.v-cdn.net\/6025736\/uploads\/favicon_556f200ac5edea81.ico","id":1}],"ts":"1505131765.000372"},"subtype":"message_changed","hidden":true,"channel":"C6M6RV472","previous_message":{"type":"message","user":"U6PDZCV9T","text":"test","ts":"1505131765.000372"},"event_ts":"1505131767.000085","ts":"1505131767.000085"}; line: 1, column: 30] (through reference chain: me.ramswaroop.jbot.core.slack.models.Event["message"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1420)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1011)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1201)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at me.ramswaroop.jbot.core.slack.Bot.handleTextMessage(Bot.java:163)
	at me.ramswaroop.jbot.core.slack.BotWebSocketHandler.handleTextMessage(BotWebSocketHandler.java:32)
	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:110)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:78)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:131)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:73)
	at org.apache.tomcat.websocket.WsFrameClient.access$300(WsFrameClient.java:31)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:131)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:114)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:463)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:332)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
Even with this exception, the bot manages to print the message on Slack without problems.

**Comment by tcarlson25** [comment] 2017-09-11 16:22
I made my code just make a GET request every 2 hours or so, and it fixed the issue.

**Comment by Lazar5555** [comment] 2017-10-10 15:23
@tcarlson25 to which URL do you make the request?

**Comment by ramswaroop** [comment] 2017-10-10 19:27
@Lazar5555 try sending an echo message every 1 hr or so using the same reply method.

**Comment by ajohnsonz** [comment] 2017-11-30 10:31
Hi guys, I'm having the same issue. After several hours of Slack not having any activity (for example overnight when noone is posting anything) the bot status changes to "away" on Slack even though the bot itself still thinks it is online. I'm running the bot on my laptop, definitely no cutoffs etc, it seems the websocket is maybe being timed out at the Slack end but the bot is not "told" that the connection has closed. @tcarlson25 can you give an example of the GET request you used? @ramswaroop I believe Slack supports a "ping / pong" system, is it possible to add this? Maybe that would solve it.

**Comment by ajohnsonz** [comment] 2017-11-30 14:29
I have added the following to my bot, it seems to have helped, but will need to run it for a few days to be sure:

```
	@Override
	public void afterConnectionEstablished(WebSocketSession session) {
        LOG.info("WebSocket is now connected: {}", session);
        LOG.info("Scheduling ping");
        
        long initialDelay = 10;
		long period = 300;
		TimeUnit unit = TimeUnit.SECONDS;
		executorService.scheduleAtFixedRate(new Runnable() {
			@Override
			public void run() {
				try {
					LOG.debug("Sending Spring PingMessage");
					session.sendMessage(new PingMessage());
				} catch (Exception e) {
					LOG.error("Could not send ping", e);
				} 			}
		}, initialDelay, period, unit);
    }
```

**Comment by ramswaroop** [comment] 2018-06-01 13:41
Guys, I am using `supervisord` to manage the jbot java process and am not seeing any such issues. It would be worth trying it. [supervisord](http://supervisord.org/) is a process manager and is responsible for keeping the process running without a significant downtime with no intervention.

**Comment by rampatra** [comment] 2018-06-17 19:36
This issue is fixed in this [commit](https://github.com/rampatra/jbot/commit/c8d86ed0e0378c20e4cb4913ec6154286f8e1dfe). Please use JBot version 4.1.0+ to circumvent this issue.

**Closed by rampatra** 2018-06-17 19:36 UTC
